nav:
  enable: true
  travelling: true
  clock: false
  menu:
    - title: 我的
      item:
        - name: 音乐馆
          link: https://music.luoh.pages.dev/
          icon: https://cdn.icon-icons.com/icons2/2201/PNG/96/apple_music_android_logo_icon_134021.png
        - name: MIKUTAP
          link: https://mikutap.luoh.pages.dev/
          icon: https://cdn.icon-icons.com/icons2/605/PNG/512/heart-rhythm_icon-icons.com_56083.png
        - name: 表情一览
          link: https://emoji-show.luoh.pages.dev/
          icon: https://cdn.icon-icons.com/icons2/2645/PNG/512/emoji_smile_icon_160172.png
        - name: Cover
          link: https://pic.chino.my.to/cover
          icon: https://cdn.icon-icons.com/icons2/390/PNG/512/book-cover_39346.png

menu:
  文章:
    分类: /categories/ || anzhiyu-icon-shapes
    标签: /tags/ || anzhiyu-icon-tags

  我的:
    闲言碎语: /essay/ || anzhiyu-icon-lightbulb
    留言板: /comments/ || anzhiyu-icon-envelope

  玩耍:
    小空调: /air-conditioner/ || anzhiyu-icon-fan
    E-木鱼: /electron-fish/ || fa-solid fa-fish

  本站:
    关于本人: /about/ || anzhiyu-icon-paper-plane
    随便逛逛: javascript:toRandomPost() || fa-solid fa-shoe-prints

highlight_theme: mac light
highlight_copy: true
highlight_shrink: false
highlight_height_limit: 300

# 作者卡片 状态
author_status:
  enable: true
  statusImg: ""
  skills:
    - 清风跃窗台
    - 明玉挂银带
    - 身居最高层
    - 侧躺把星摘

# 标签卖萌
diytitle:
  enable: false
  leaveTitle: w(ﾟДﾟ)w 不要走！再看看嘛！
  backTitle: ♪(^∇^*)欢迎肥来！

# 打赏二维码
reward:
  enable: true
  coinAudio: https://cdn.cbd.int/luoh-blog-static@0.0.5/audio/aowu.m4a
  QR_code:
    - img: https://cdn.cbd.int/luoh-blog-static@0.0.5/image/qrcode-wechat.png
      link:
      text: wechat

# 欢迎语配置
greetingBox:
  enable: false
  default: 晚上好👋
  list:
    - greeting: 晚安😴
      startTime: 0
      endTime: 5
    - greeting: 早上好鸭👋, 祝你一天好心情！
      startTime: 6
      endTime: 9
    - greeting: 上午好👋, 状态很好，鼓励一下～
      startTime: 10
      endTime: 10
    - greeting: 11点多啦, 在坚持一下就吃饭啦～
      startTime: 11
      endTime: 11
    - greeting: 午安👋, 宝贝
      startTime: 12
      endTime: 14
    - greeting: 🌈充实的一天辛苦啦！
      startTime: 14
      endTime: 18
    - greeting: 19点喽, 奖励一顿丰盛的大餐吧🍔。
      startTime: 19
      endTime: 19
    - greeting: 晚上好👋, 在属于自己的时间好好放松😌~
      startTime: 20
      endTime: 24  

# 动效
dynamicEffect:
  postTopWave: true
  postTopRollZoomInfo: true
  pageCommentsRollZoom: true

runtimeshow:
  enable: true
  publish_date: 4/23/2024 00:00:00

# A simple 404 page
error_404:
  enable: true
  subtitle: "怪兽把页面拖走了..."
  background: https://cdn.cbd.int/luoh-blog-static@0.0.7/image/gif/404.gif #https://pic.chino.my.to/i/2024/07/31/448691.gif

icons:
  fontawesome: true

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover: 

social:
  Github: https://github.com/enlt  anzhiyu-icon-github
  Telegram: https://t.me/zlorix  anzhiyu-icon-telegram  
  QQ: mqqwpa://im/chat?chat_type=wpa&uin=1412219758  anzhiyu-icon-qq

post_meta:
  page:
    date_type: both
    date_format: relative
    categories: true
    tags: true
    label: true
  post:
    date_type: both
    date_format: relative
    categories: true 
    tags: true
    label: true 

post_copyright:
  enable: true
  decode: false
  author_href:
  location: 中国
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

related_post:
  enable: true
  limit: 3
  date_type: created

translate:
  enable: false
  default: 繁
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: "繁"
  msgToSimplifiedChinese: "简"

readmode: false

aside:
  enable: true               # 是否启用侧边栏
  hide: false                # 是否隐藏侧边栏
  button: true               # 是否显示侧边栏按钮
  mobile: true               # 是否在移动设备上显示侧边栏
  position: right            # 侧边栏位置，left 或 right
  display:                   # 控制对应详情页面是否显示侧边栏
    archive: true            # 是否在归档页面显示
    tag: true                # 是否在标签页面显示
    category: true           # 是否在分类页面显示
  card_author:
    enable: true           # 是否启用作者卡片
    description: <div style="text-align:center">清风跃窗台<br>明玉挂银带<br>身居最高层<br>侧躺把星摘</div>
    name_link: /about        # 作者链接
  card_announcement:
    enable: false
    content: 推荐使用Edge浏览器访问本站 # <img src='https://api.luoh.my.to/daysign.php'>   # 公告内容
  card_weixin:
    enable: false             # 是否启用微信卡片
    face:      # 正面图片链接
    backFace: # 背面图片链接
  card_recent_post:
    enable: false             # 是否启用最新文章卡片
    limit: 9                 # 显示文章数量，设置为0则显示全部
    sort: date               # 排序方式，date 或 updated
    sort_order:              # 排序顺序，不要修改这个设置除非你知道它是如何工作的
  card_categories:
    enable: false            # 是否启用分类卡片
    limit: 8                 # 显示分类数量，设置为0则显示全部
    expand: none             # 展开方式，none/true/false
    sort_order:              # 排序顺序，不要修改这个设置除非你知道它是如何工作的
  card_tags:
    enable: true             # 是否启用标签卡片
    limit: 40                # 显示标签数量，设置为0则显示全部
    color: true             # 是否使用颜色
    sort_order:              # 排序顺序，不要修改这个设置除非你知道它是如何工作的
    highlightTags:           # 高亮标签
  card_archives:
    enable: true             # 是否启用归档卡片
    type: monthly            # 归档类型，yearly 或 monthly
    format: MMMM YYYY        # 格式，例如：YYYY年MM月
    order: -1                # 排序方式，1表示升序，-1表示降序
    limit: 8                 # 显示数量，设置为0则显示全部
    sort_order:              # 排序顺序，不要修改这个设置除非你知道它是如何工作的
  card_webinfo:
    enable: true             # 是否启用网站信息卡片
    post_count: true         # 是否显示文章计数
    last_push_date: false    # 是否显示最后推送日期
    sort_order:              # 排序顺序，不要修改这个设置除非你知道它是如何工作的

pangu:
  enable: true
  field: post

comments:
  use: Twikoo
  text: true
  lazyload: false
  count: true
  card_post_count: false

twikoo:
  envId: https://enltic-twikoo.hf.space/
  region: ap-shanghai
  visitor: false  
  option:
  
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true
  
# waline:
  # serverURL: https://waline-five-sand.vercel.app/ui/login# Waline server address url
  # bg: # waline background
  # pageview: false
  # option:  

# Loading Animation (加载动画)
preloader:
  enable: true
  source: 3
  pace_css_url:
  avatar: https://i1.wp.com/cdn.cbd.int/luoh-blog-static@0.0.7/image/gif/avatar.gif #https://cravatar.cn/avatar/7bd408da64452102b343f062e9f091c0

# 评论匿名邮箱
visitorMail:
  enable: true
  mail: visitor@luo.to

fancybox: true
#medium_zoom: true

# 快捷键配置
shortcutKey:
  enable: true
  delay: 100 # 所有键位延时触发而不是立即触发（包括shift，以解决和浏览器键位冲突问题）
  shiftDelay: 200 # shift按下延时多久开启  

# 右键菜单
rightClickMenu:
  enable: true

# 随便逛逛people模式
peoplecanvas:
  enable: false
  img:

home_top:
  enable: true # 开关
  timemode: date #date/updated
  title: 一缕红线落人间
  subTitle: 半壶清酒破三弦
  siteText: 仅望得君欢
  category:
    - name: 标签
      path: /tags/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-dove
    - name: 分类
      path: /categories/
      shadow: var(--anzhiyu-shadow-red)
      class: red
      icon: anzhiyu-icon-fire
    - name: 归档
      path: /archives/
      shadow: var(--anzhiyu-shadow-green)
      class: green
      icon: anzhiyu-icon-book
  default_descr: 万军争战于世间
  swiper:
    enable: false
    swiper_css: https://cdn.cbd.int/anzhiyu-theme-static@1.0.0/swiper/swiper.min.css #swiper css依赖
    swiper_js: https://cdn.cbd.int/anzhiyu-theme-static@1.0.0/swiper/swiper.min.js #swiper js依赖
  banner:
    tips: TOP
    title: 花间一壶酒，剑客于千秋。
    image: https://cdn.cbd.int/luoh-blog-static@0.0.8/image/webp/banner-image.webp #https://cdn.jsdmirror.com/gh/snxdm/picgo@main/2024/1722229480952.webp
    link: https://luoh.pages.dev/

agreementPopup:
  enable: true
  url: /privacy

# cloudflare_analytics: 902ecdcc7f2347fca972213c3688b1ac
google_analytics: G-KZQLNK8CS7

nav_music:
  enable: false
  console_widescreen_music: false
  id: 9216803294
  server: tencent
  all_playlist: https://y.qq.com/n/ryqq/playlist/9216803294

# CDN
# 非必要请不要修改
CDN:
  internal_provider: cbd
  third_party_provider: cbd
  option:
    meting_api: https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r
    twikoo: https://cdn.cbd.int/twikoo@1.6.39/dist/twikoo.all.min.js
    busuanzi: https://cdn.cbd.int/penndu@1.0.0/bsz.js

# dark mode
darkmode:
  enable: true
  button: true
  autoChangeMode: 1
  start: 8
  end: 22

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq #想要显示的内容  
  
# 双栏文章
article_double_row: true

mourn:
  enable: true
  days: [4-4, 7-7, 9-18, 12-13]

avatar:
  img: https://i1.wp.com/cdn.cbd.int/luoh-blog-static@0.0.7/image/gif/avatar.gif #https://cravatar.cn/avatar/7bd408da64452102b343f062e9f091c0
  effect: false

toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false # for post

mainTone:
  enable: true
  mode: api 
  api: https://api.qjqq.cn/api/Imgcolor?img=
  cover_change: true

# 留言弹幕配置
# comment_barrage_config:
  # enable: true
  # maxBarrage: 1
  # barrageTime: 8000
  # accessToken: "8a7ef65d0a45454fb3e170149f5f9f1a"
  # mailMd5: "4304d02503b34d3d8b7bfd123ccfc9fc"

# Footer Settings
footer:
  owner:
    enable: true
    since: 2023
  custom_text:
  runtime:
    enable: false
    launch_time: 04/23/2024 00:00:00 # 网站上线时间
    work_img: https://cdn.cbd.int/luoh-blog-static@0.0.1/image/落渐离-苦逼学生者.svg
    work_description: 在下乃苦逼学生者
    offduty_img: https://cdn.cbd.int/luoh-blog-static@0.0.1/image/落渐离-苦逼学生者.svg
    offduty_description: 在下乃苦逼学生者
  # 徽标部分配置项
  bdageitem:
    enable: true
    list:
      - link: https://hexo.io/ #徽标指向网站链接
        shields: https://cdn.cbd.int/anzhiyu-blog@2.1.5/img/badge/Frame-Hexo.svg #徽标API
        message: 博客框架为Hexo #徽标提示语
      - link: https://cdn.cbd.int/
        shields: https://cdn.cbd.int/luoh-blog-static@0.1.4-rc.2/image/svg/CDN-Unpkg-green.svg
        message: 本站使用Unpkg为静态资源提供CDN加速
      - link: https://github.com/
        shields: https://cdn.cbd.int/anzhiyu-blog@2.1.5/img/badge/Source-Github.svg
        message: 本站项目由Github托管
      - link: https://github.com/anzhiyu-c/hexo-theme-anzhiyu
        shields: https://cdn.cbd.int/anzhiyu-theme-static@1.0.9/img/Theme-AnZhiYu-2E67D3.svg
        message: 本站使用AnZhiYu主题
      - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
        shields: https://cdn.cbd.int/anzhiyu-blog@2.2.0/img/badge/Copyright-BY-NC-SA.svg
        message: 本站采用知识共享署名-非商业性使用-相同方式共享4.0国际许可协议进行许可
  socialBar:
    enable: true
    centerImg:
    left:
      - title: email
        link: mailto:enltic@outlook.com
        icon: anzhiyu-icon-envelope
      - title: RSS
        link: atom.xml
        icon: anzhiyu-icon-rss
    right:
      - title: Github
        link: https://github.com/enlt
        icon: anzhiyu-icon-github
      - title: CC
        link: /copyright
        icon: anzhiyu-icon-copyright-line
  list:
    enable: true
    randomFriends: 0
    project:
      - title: 服务
        links:
          - title: 不蒜子
            link: https://dusays.com/476/
          - title: Unpkg
            link: https://cdn.cbd.int/
          - title: luohAPI
            link: https://api.luoh.my.to/
      - title: 导航
        links:
          - title: 即刻短文
            link: /essay/
          - title: 随听音乐
            link: https://music.luoh.pages.dev/
          - title: 留言板
            link: /comments/
      - title: 协议
        links:
          - title: 隐私协议
            link: /privacy/
          - title: Cookies
            link: /cookies/
          - title: 版权协议
            link: /copyright/
  footerBar:
    enable: true
    cc:
      enable: true
    linkList:
      - link: https://github.com/anzhiyu-c/hexo-theme-anzhiyu
        text: 主题

# 51a统计配置
LA:
  enable: false
  ck: # 3J4jpflGza04donK
  LingQueMonitorID: # 3JBt9UjSP6o0Fuqu

local_search:
  enable: true
  preload: true
  CDN:

theme_color:                   # 主题颜色配置的开始
  enable: true                 # 启用主题颜色功能
  main: "#425AEF"              # 主要的颜色，用于突出显示和按钮等重要元素
  dark_main: "#a5bda2"         # 暗色模式下的主要颜色
  paginator: "#425AEF"         # 分页器（如页面导航）的颜色
  # button_hover: "#FF7242"     # 鼠标悬停在按钮上时的颜色，这里被注释掉了，表示不使用
  text_selection: "#2128bd"    # 文本选中时的背景颜色
  link_color: "var(--anzhiyu-fontcolor)" # 链接的颜色，使用预定义的变量
  meta_color: "var(--anzhiyu-fontcolor)" # 元数据（如日期、作者信息）的颜色
  hr_color: "#4259ef23"        # 水平线（分隔线）的颜色
  code_foreground: "#fff"     # 代码块中的文字颜色
  code_background: "var(--anzhiyu-code-stress)" # 代码块的背景颜色
  toc_color: "#425AEF"         # 目录（Table of Contents）的颜色
  # blockquote_padding_color: "#425AEF" # 引用块的内边距颜色，这里被注释掉了
  # blockquote_background_color: "#425AEF" # 引用块的背景颜色，这里也被注释掉了
  scrollbar_color: "var(--anzhiyu-scrollbar)" # 滚动条的颜色
  meta_theme_color_light: "#f7f9fe" # 元数据在亮色模式下的背景颜色
  meta_theme_color_dark: "#18171d"  # 元数据在暗色模式下的背景颜色  
  
inject:
  head:
    - <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.1.3-rc.1/css/font.css"> # 字体
    - <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.0.2/css/home.css"> # 首页文章卡片擦亮效果
    - <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.1.5-rc.2/css/SomeBeautify.css">
    #- <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.0.2/css/welcome.css"> # 个性定位欢迎
    #- <link rel="stylesheet" href="https://cdn.cbd.int/luoh-blog-static@0.0.2/css/custom.css" media="defer" onload="this.media='all'">
    - <link rel="stylesheet" href="https://cdn.cbd.int/cn-fontsource-lxgw-wen-kai-gb-screen/font.css"></link>
    - <link rel="stylesheet" href="https://cdn.cbd.int/sweetalert2@11.12.4/dist/sweetalert2.min.css"> # 弹窗
  bottom:
    - <script type="text/javascript" src="https://unpkg.zhimg.com/jquery@latest/dist/jquery.min.js"></script> # jquery.min.js
    #- <script defer="true" src="https://cdn.cbd.int/luoh-blog-static@0.0.2/js/welcome.js"></script> # 个性定位欢迎信息
    #- <script async data-pjax src="https://cdn.cbd.int/luoh-blog-static@0.0.2/js/imgloaded.js"></script> # 首页图片渐进式加载
    - <script src="https://cdn.cbd.int/sweetalert2@11.12.4"></script> # 弹窗
    - <script src="https://cdn.cbd.int/luoh-blog-static@0.1.5-rc.3/js/swal2.js"></script> # 弹窗
lazyload:
  enable: true
  field: post
  placeholder: https://cdn.cbd.int/luoh-blog-static@0.1.4-rc.5/image/gif/loading.gif
  blur: true
  progressive: true
  extend:
    page: true

# 中控台
centerConsole:
  enable: false
  card_tags:
    enable: false
  card_archives:
    enable: false
    
# ptool 文章底部工具
ptool:
  enable: true
  share_mobile: true
  share_weibo: true
  share_copyurl: true
  categories: false # 是否显示分类
  mode: # 运营模式与责任，不配置不显示

# Mouse click effects: words (鼠标点击效果: 文字)
# ClickShowText:
  # enable: true
  # text:
    # - 富强
    # - 民主
    # - 文明
    # - 和谐
    # - 自由
    # - 平等
    # - 公正
    # - 法治
    # - 爱国
    # - 敬业
    # - 诚信
    # - 友善
  # fontSize: 15px
  # random: false
  # mobile: true

# Footer Background
footer_bg: false

microsoft_clarity: oblr42fxsq

# 文章顶部ai摘要
post_head_ai_description:
  enable: true
  gptName: LuoH
  mode: local # 默认模式 可选值: tianli/local
  switchBtn: false # 可以配置是否显示切换按钮 以切换tianli/local
  btnLink: https://luoh.pages.dev/
  randomNum: 3 # 按钮最大的随机次数，也就是一篇文章最大随机出来几种
  basicWordCount: 1000 # 最低获取字符数, 最小1000, 最大1999
  key: x
  Referer: https://xx.xx/