name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: false  # 禁用子模块同步

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Hexo
      run: npm install hexo-cli -g

    - name: Install dependencies
      run: npm install

    - name: Clean files
      run: hexo clean

    - name: Generate static files
      run: hexo generate

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f public/
        COMMIT_MESSAGE=$(date +"%Y-%m-%d %H:%M:%S")
        git commit -m "$COMMIT_MESSAGE"
        git push -f origin `git subtree split --prefix public main`:gh-pages